const achievements = [
  {
    id: 1,
    path: '/achievements/compress/50.jpg',
    originalFilePath: '/achievements/50.jpg',
    description: 'Участие в Международном профессиональном педагогическом конкурсе «Логопед. Высшая квалификация 2022»  (2022 г., диплом I место)',
  },
  {
    id: 2,
    path: '/achievements/compress/51.jpg',
    originalFilePath: '/achievements/51.jpg',
    description: 'Участие во Всероссийском конкурсе "Методические разработки педагогов" (2022 г., диплом победителя III степени)',
  },
  {
    id: 3,
    path: '/achievements/compress/52.jpg',
    originalFilePath: '/achievements/52.jpg',
    description: 'Участие в вебинаре «ООП-2023: корректировка основной образовательной программы детского сада с учетом актуальных тенденций в образовании»  (2022 г., сертификат)',
  },
  {
    id: 4,
    path: '/achievements/compress/54.jpg',
    originalFilePath: '/achievements/54.jpg',
    description: 'Прохождение всероссийского тестирования по теме "Оценка компетентности учителей-логопедов" (2022 г., 100 баллов, сертификат)',
  },
  {
    id: 5,
    path: '/achievements/compress/53.jpg',
    originalFilePath: '/achievements/53.jpg',
    description: 'Участие во всероссийском конкурсе "Нормативно-правовая подготовленность учителя-логопеда" (2022 г., диплом I место)',
  },
  {
    id: 6,
    path: '/achievements/compress/55.jpg',
    originalFilePath: '/achievements/55.jpg',
    description: 'Участие во Всероссийском вебинаре «Постановка и активация главных звуков у детей с ТНР как база для успешной речевой коммуникации»  (2022 г., сертификат)',
  },
  {
    id: 7,
    path: '/achievements/compress/57.jpg',
    originalFilePath: '/achievements/57.jpg',
    description: 'Участие во Всероссийском вебинаре «Наиболее частые ошибки в логопедической работе»  (2022 г., сертификат)',
  },
  {
    id: 8,
    path: '/achievements/compress/58.jpg',
    originalFilePath: '/achievements/58.jpg',
    description: 'Участие в Международном профессиональном педагогическом конкурсе «Логопед. Высшая квалификация 2022»  (2022 г., диплом I место)',
  },
  {
    id: 9,
    path: '/achievements/compress/60.jpg',
    originalFilePath: '/achievements/60.jpg',
    description: 'Куратор воспитанников во всероссийской викторине «Путешествие по сказкам К.И. Чуковского» (2022 г., дипломы I место)',
  },
  {
    id: 10,
    path: '/achievements/compress/27.jpg',
    originalFilePath: '/achievements/27.jpg',
    description: 'Участие во Всероссийском вебинаре «Использование настольных игр на развивающих и коррекционных занятиях с детьми»  (2021 г., сертификат)',
  },
  {
    id: 11,
    path: '/achievements/compress/29.jpg',
    originalFilePath: '/achievements/29.jpg',
    description: 'Участие во Всероссийском конкурсе «Праздник правильной речи» (для учителей-логопедов) (2021 г., диплом I место)',
  },
  {
    id: 12,
    path: '/achievements/compress/30.jpg',
    originalFilePath: '/achievements/30.jpg',
    description: 'Участие во Всероссийском вебинаре «Стимуляция развития осознанности и пространственных представлений у детей: приемы и методы формирования схемы тела»  (2021 г., сертификат)',
  },
  {
    id: 13,
    path: '/achievements/compress/31.jpg',
    originalFilePath: '/achievements/31.jpg',
    description: 'Участие во Всероссийском вебинаре «Новые технологии взаимодействия и обучения детей с РАС и ментальными особенностями с помощью программы "А-Спектр"»  (2021 г., сертификат)',
  },
  {
    id: 14,
    path: '/achievements/compress/33.jpg',
    originalFilePath: '/achievements/33.jpg',
    description: 'Участие во Всероссийском профессиональном конкурсе для педагогов  «Педагогика ХХI века»  (2021 г., диплом 2 место)',
  },
  {
    id: 15,
    path: '/achievements/compress/32.jpg',
    originalFilePath: '/achievements/32.jpg',
    description: 'Участие во Всероссийском вебинаре «Современные лого-технологии развития фонематического восприятия у детей с ОВЗ»  (2021 г., сертификат)',
  },
  {
    id: 16,
    path: '/achievements/compress/34.jpg',
    originalFilePath: '/achievements/34.jpg',
    description: 'Участие во Всероссийском вебинаре «Коррекция поведения дошкольников с ОВЗ. Современные тенденции»  (2021 г., сертификат)',
  },
  {
    id: 17,
    path: '/achievements/compress/35.jpg',
    originalFilePath: '/achievements/35.jpg',
    description: 'Участие в  вебинаре «Как преодолеть нарушения звукопроизношения и предупредить дисграфию?» (2021 г., сертификат)',
  },
  {
    id: 18,
    path: '/achievements/compress/36.jpg',
    originalFilePath: '/achievements/36.jpg',
    description: 'Участие во II Всероссийском форуме "Воспитатели России" (2021 г., сертификат)',
  },
  {
    id: 19,
    path: '/achievements/compress/37.jpg',
    originalFilePath: '/achievements/37.jpg',
    description: 'Участие в  вебинаре «Совершенствуем и закрепляем у детей 5-7 лет практические знания и способности к анализу и синтезу языкового материала (звуки, буквы, слоги, слова)» (2021 г., сертификат)',
  },
  {
    id: 20,
    path: '/achievements/compress/38.jpg',
    originalFilePath: '/achievements/38.jpg',
    description: 'Участие во Всероссийском конкурсе «Лучший сайт педагога - 2021»  (2021 г., диплом III степени)',
  },
  {
    id: 21,
    path: '/achievements/compress/39.jpg',
    originalFilePath: '/achievements/39.jpg',
    description: 'Участие в Международном конкурсе знаний «Логопед. Высшая квалификация 2021»  (2021 г., диплом I место)',
  },
  {
    id: 22,
    path: '/achievements/compress/40.jpg',
    originalFilePath: '/achievements/40.jpg',
    description: 'Участие во Всероссийской онлайн-конференции "Предметная неделя: подводим итоги учебного года, определяем перспективы. День педагога дошкольного образования". (2021 г., сертификат)',
  },
  {
    id: 23,
    path: '/achievements/compress/42.jpg',
    originalFilePath: '/achievements/42.jpg',
    description: 'Участие во Всероссийском форуме "Воспитатели России" "Воспитаем здорового ребенка. Цифровая эпоха" (2021 г., сертификат)',
  },
  {
    id: 24,
    path: '/achievements/compress/43.jpg',
    originalFilePath: '/achievements/43.jpg',
    description: 'Участие во Всероссийском вебинаре «Активизация речи у детей с 1-2 уровнем речевого развития. Принцип обходного пути»  (2021 г., сертификат)',
  },
  {
    id: 25,
    path: '/achievements/compress/45.jpg',
    originalFilePath: '/achievements/45.jpg',
    description: 'Участие во ВСЕРОССИЙСКОМ ИССЛЕДОВАНИИ КАЧЕСТВА И ПЕРСПЕКТИВЫ РАЗВИТИЯ ДИСТАНЦИОННОГО ОБУЧЕНИЯ «МЕТАМОРФОЗЫ В ЭПОХУ ЦИФРОВЫХ ТЕХНОЛОГИЙ»  (2021 г., сертификат)',
  },
];

export default achievements;
